brokers:
  ci:
    url: "failover:(ssl://your.broker1:12345,ssl://your.broker2:12345)"
    user: foo
    password: blah
    messages:
      timeout: 300000
      maxMsgs: 2
    tls:
      keystore-path: "/path/to/your/keystore.jks"  # Path to the .jks keystore
      truststore-path: "/path/to/your/truststore.jks"       # Path to the .jks truststore
      keystorekey-pw: "pw-of-pvtkey-tokeystore"             # Password of the private key (from the .p12 file)
      keystore-pw: "pw-of-keystore"                         # Password of the keystore file (jks)
      truststore-pw: "pw-of-truststore"                     # Password of the truststore file
  metrics:
    url: "another.server.com:65432"
    user: "foo"
    password: "bar"
    messages:
      timeout: 1000
      maxMsgs: 1
defaultBroker: ci
